### ISSUE TITLE
Will authentication be covered?

### ISSUE THREAD

**Issue by davidpeden3** [freshcutdevelopment/Aurelia-in-Action#1]
It would be great to cover how to properly and securely integrate [OpenID Connect](http://openid.net/connect/) authentication into your sample app. Presumably this would be covered under the Routing chapter?

I've not personally used [this repo](https://github.com/shaunluttin/aurelia-open-id-connect) (and therefore am not specifically endorsing it), but this adapter looks like a  good example of what I'm talking about and leverages a fairly popular client to integrate with a popular STS called [Identity Server](https://identityserver.io). Identity Server is widely used in the .NET community.

Obviously configuring your own [STS](https://en.wikipedia.org/wiki/Security_token_service) would be beyond the scope of the topic but I think integrating with an existing server as mentioned (or service like [Auth0](https://auth0.com)) would be fantastic.

Perhaps a collaborative effort with @shaunluttin would be great as well. ;)

**Comment by freshcutdevelopment** [comment]
Thanks @davidpeden3, yes will be covering authentication in chapter 9 - routing. Not sure exactly the shape that this will take at this point but will take a look through this repo as well.

**Comment by davidpeden3** [comment]
Great! You might want to consider making authentication its own chapter. Those not specifically familiar with Aurelia already may not know that authentication falls under routing.

**Comment by freshcutdevelopment** [comment]
Thanks @davidpeden3 , that's a good point. I'll keep that in mind as chapter 9 progresses, would definitely be more clear from a Table of Contents point of view.

**Comment by freshcutdevelopment** [comment]
Hi @davidpeden3, just wanted to give you the latest update on this. I ended up splitting this into two chapters, routing, and authentication. Your suggestion to split them ended up being a great idea, as there was so much to cover in either of these two topics alone. 

These chapters are now available as a part of the MEAP [Chapter 9 - routing](https://livebook.manning.com/#!/book/aurelia-in-action/chapter-9/v-4/), [Chapter 10 -
 authentication](https://livebook.manning.com/#!/book/aurelia-in-action/chapter-10/v-4/).  Would be interested in any feedback you've got :D

**Comment by davidpeden3** [comment]
@freshcutdevelopment Excellent. Thanks for the update!
