### ISSUE TITLE
Figures in kindle format are extremely blurry

### ISSUE THREAD

**Issue by davidpeden3** [freshcutdevelopment/Aurelia-in-Action#10]
I'm running the kindle software on an iPad Pro and the figures are virtually impossible to make out. I've attached an example (figure 3.4).
![img_0240](https://user-images.githubusercontent.com/1190710/35819879-9d397024-0a69-11e8-9bb0-476cc07559a4.PNG)

**Comment by freshcutdevelopment** [comment]
Thanks David, I see what you mean. Thanks for rasing this. I've not tested it on that resolution but clearly there is an issue. I'll see what we can do about getting these images updated to work better for this format.

Cheers,
Sean

**Comment by freshcutdevelopment** [comment]
Hi David,

I just wanted to give you an update on this. As a part of the production process, each of the images is being tweaked and improved by the art team. We should see them come out with better resolution which will help with this issue. I'll leave the ticket open and review once they've completed there part.

Cheers,
Sean

**Comment by freshcutdevelopment** [comment]
All images replaced with vectors as a part of the production process. This issue should now be resolved.
