### ISSUE TITLE
tokenInterceptor should be called in withInterceptor

### ISSUE THREAD

**Issue by MrTango** [freshcutdevelopment/Aurelia-in-Action#13]
`this.authService.tokenInterceptor` 
should be 
`this.authService.tokenInterceptor`()

https://github.com/freshcutdevelopment/Aurelia-in-Action/blob/0b447630d3cab39b38dda62a249002b3af05516c/Chapter-10-Complete/my-books/src/app.js#L17

**Comment by freshcutdevelopment** [comment]
Thanks for the heads up Maik. Will adjust accordingly .

**Comment by freshcutdevelopment** [comment]
Hi Maik,

Actually, since this call is to `tokenInteptor` which is a getter. This doesn't need brackets:

```js
    get tokenInterceptor(){
        let auth = this;
        return {
            request(request) {
                let token = auth.getToken();
                if(token){
                    request.headers.append('authorization', `bearer ${token}`);
                }
                return request; 
            }
        };
    }
```
