### ISSUE TITLE
Chapter 6 and 7 code

### ISSUE THREAD

**Issue by asichi** [freshcutdevelopment/Aurelia-in-Action#3]
I am reading the book and following along in the code.  Up to Chapter 5 complete, the code works great. I run npm install and then au run --watch and all is well. When I tried to do the same with Chapter 6 and 7, npm install works without errors or warnings, but I only get a blank page when I go to localhost:9000.  Any ideas on how to debug?

**Comment by asichi** [comment]
This seemed to be an issue with the bootstrap version. Npm installed bootstrap@4.0.0-beta.  I deleted it and installed bootstrap@4.0.0-aplha.6 and it is working now as expected.

**Comment by freshcutdevelopment** [comment]
Hi Asichi,

Thanks for the feedback. I'll also be updating the book to use the Beta version instead to make this more intuitive going forward.

Cheers,
Sean
